In [1]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.lines import Line2D
from pylab import rcParams
rcParams['figure.figsize'] = 25, 10
import numpy as np 
import dill as pickle
import os
import random
import datetime 
import sys 
import seaborn as sns
from einops import rearrange
import matplotlib as mpl
from matplotlib.patches import Rectangle
mpl.rcParams['text.usetex'] = True
mpl.rcParams['text.latex.preamble'] = [r'\usepackage{amsmath}'] #for \text command

np.random.seed(0)
random.seed(0)
now = datetime.datetime.now().strftime("%B_%d_%Y_%H_%M_%S")
workingdirectory = os.popen('git rev-parse --show-toplevel').read()[:-1]
sys.path.append(workingdirectory)
os.chdir(workingdirectory)

from codes.flasso.Replicate import Replicate
from codes.experimentclasses.AtomicRegression2 import AtomicRegression
from codes.otherfunctions.get_cosines import get_cosines
from codes.plotting.supportrecovery import plot_watch3,plot_reg_path_ax_lambdasearch_customcolors_norm
from itertools import combinations

def get_names(subset):
    
    names = np.zeros(len(subset), dtype = object)
    for s in range(len(subset)):
        names[s] = r"$g_{{{}}}$".format(subset[s])
    return(names)

def get_color_subset(color_superset, superset, subset):
    
    colors_subset = np.zeros((len(subset),4 ))
    print(subset.shape,colors_subset.shape)
    for s in range(len(subset)):
        colors_subset[s] = color_superset[np.where(superset == subset[s])[0]] 
    return(colors_subset)

In [4]:
from codes.flasso.GradientGroupLasso import get_sr_lambda_sam_parallel


In [7]:

gl_itermax = 5000
max_search = 30
reg_l2 = 0.
tol = 1e-14
learning_rate = 100
dim = 2
for r in range(1):
    ul = np.linalg.norm(np.einsum('n d m, n d p -> n p m ', replicates[r].df_M, replicates[r].dg_M),
                        axis=tuple([0, 2])).max()
    lambdas_start = [0., ul]
    replicates[r].results2 = get_sr_lambda_sam_parallel(replicates[r], gl_itermax, lambdas_start, reg_l2, max_search,
                                                       dim, tol, learning_rate)


initializing lambda search
converged 1088.3520817054798
0 544.1760408527399 probe
1 816.2640612791099 probe
converged 816.2640612791099
2 952.3080714922949 probe
converged 952.3080714922949
we did it [196 745]


In [ ]:
downsample_indices  = np.asarray([])

In [110]:
atoms4

NameError: name 'atoms4' is not defined

In [155]:
def get_indices_matching_modulo(search_atoms4 , target_atoms4):
    
    nsearch = search_atoms4.shape[0]
    output = np.zeros(search_atoms4.shape[0])
    for n in range(nsearch):
         probes = np.asarray([search_atoms4[n,[0, 1, 2, 3]],
                              search_atoms4[n,[0,2,1,3]],
                             search_atoms4[n,[3,1,2,0]],
                              search_atoms4[n,[3,2,1,0]]])
        
         output[n] = np.concatenate([np.where((target_atoms4 == probes[p]).all(axis=1))[0] for p in range(4)])
    return(np.asarray(output, dtype = int))

In [156]:
get_indices_matching_modulo(search_atoms4 , target_atoms4)

array([ 14,  44,  68,  20,  50,  74,  26,  56,  80,  31, 152, 176])

In [113]:
ii = np.asarray([0, 0, 0, 0, 1, 1, 1, 2])  # atom adjacencies for dihedral angle computation
jj = np.asarray([1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
from codes.otherfunctions.get_dictionaries import get_atoms_4, get_all_atoms_4

In [116]:
atoms4_diagram, p = get_atoms_4(9, ii, jj)

In [119]:
atoms4_full, p = get_all_atoms_4(9)

In [121]:
search_atoms4 = atoms4_diagram
target_atoms4 = atoms4_full

In [158]:
diagram_ind = get_indices_matching_modulo(search_atoms4 , target_atoms4)

In [159]:
p = 756

In [165]:
possibilities = np.asarray(np.setdiff1d(np.asarray(list(range(p))), diagram_ind))

In [166]:
import random

In [178]:
keepind[:50]

array([ 14,  44,  68,  20,  50,  74,  26,  56,  80,  31, 152, 176, 734, 628, 161, 329, 111])

In [182]:
#let us gaze into the malonaldehyde:
with open('/Users/samsonkoelle/manifoldflasso_jmlr/untracked_data/embeddings/ethanol/ethanol_0219_fullreplicates_small_abscos.pkl' ,
         'rb') as loader:
     replicates = pickle.load(loader)


In [183]:

gl_itermax = 500
max_search = 30
reg_l2 = 0.
tol = 1e-14
learning_rate = 100
dim = 2
for r in range(5):
    rs = random.sample(list(possibilities), 5)
    keepind = diagram_ind#np.concatenate([diagram_ind, rs])
    replicates[r].dg_M = replicates[r].dg_M[:,:,keepind]
    ul = np.linalg.norm(np.einsum('n d m, n d p -> n p m ', replicates[r].df_M, replicates[r].dg_M),
                        axis=tuple([0, 2])).max()
    lambdas_start = [0., ul]
    replicates[r].results2 = get_sr_lambda_sam_parallel(replicates[r], gl_itermax, lambdas_start, reg_l2, max_search,
                                                       dim, tol, learning_rate)


initializing lambda search
converged 756.9995925019307
0 378.49979625096535 probe
converged 378.49979625096535
we did it [0 9]
initializing lambda search
converged 787.3482569623073
0 393.6741284811537 probe
converged 393.6741284811537
we did it [0 9]
initializing lambda search
converged 750.2825399738872
0 375.1412699869436 probe
converged 375.1412699869436
we did it [0 9]
initializing lambda search
converged 801.1151694898494
0 400.5575847449247 probe
converged 400.5575847449247
we did it [0 9]
initializing lambda search
converged 747.2745413000712
0 373.6372706500356 probe
converged 373.6372706500356
we did it [ 0 11]


In [10]:
import sys
!{sys.executable} -m pip install sympy

     |████████████████████████████████| 5.8 MB 1.3 MB/s eta 0:00:01
     |████████████████████████████████| 532 kB 17.1 MB/s eta 0:00:01


In [13]:
import sys
!{sys.executable} -m pip install pycartan==0.1.5

  Using cached pycartan-0.1.5.tar.gz (16 kB)
  Created wheel for pycartan: filename=pycartan-0.1.5-py3-none-any.whl size=16652 sha256=39e99bc4d4ffc29f9855056474d3558c657bed1ac2c8b9abe599faf213c5fcde
  Stored in directory: /Users/samsonkoelle/Library/Caches/pip/wheels/68/58/49/f28b699f4ac19f616e14802fccd53207b02f4d99eaa8c28cf5
Successfully built pycartan


In [12]:
import sys
!{sys.executable} -m pip install symbtools

     |████████████████████████████████| 115 kB 4.1 MB/s eta 0:00:01
  Created wheel for symbtools: filename=symbtools-0.3.1-py2.py3-none-any.whl size=129670 sha256=9d538be76ffff2bc6e6e260eba2e4fc204ec9827ca86a306b5fdb51372ed8602
  Stored in directory: /Users/samsonkoelle/Library/Caches/pip/wheels/54/93/42/3d0e57dbced34850f0b6b7d145fd485bcaf6c26fba978783a6
  Created wheel for ipydex: filename=ipydex-0.11.3-py3-none-any.whl size=29357 sha256=fb2389acc79fc420154c9a58ec27fddf98788dbefff25756d63b9a3c74bd1f97
  Stored in directory: /Users/samsonkoelle/Library/Caches/pip/wheels/01/de/b0/5177778a5dfa50666b2bb410157f8af68ff8d0061e0b6c9d9f
Successfully built symbtools ipydex


In [15]:
import pycartan

In [16]:
help(pycartan)

Help on package pycartan:

NAME
    pycartan - # -*- coding: utf-8 -*-

PACKAGE CONTENTS
    core
    release

FUNCTIONS
    reduce(...)
        reduce(function, sequence[, initial]) -> value
        
        Apply a function of two arguments cumulatively to the items of a sequence,
        from left to right, so as to reduce the sequence to a single value.
        For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
        ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
        of the sequence in the calculation, and serves as a default when the
        sequence is empty.

DATA
    string_types = (<class 'str'>,)

VERSION
    0.1.5

FILE
    /Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/pycartan/__init__.py




In [19]:
import pycartan as pc

In [97]:
(x1, x2, x3), (dx1, dx2, dx3) = pc.setup_objects(2)

ValueError: not enough values to unpack (expected 3, got 2)

In [99]:
type(dx3)

pycartan.core.DifferentialForm

In [94]:
hs = dx1.hodge_star()

In [95]:
hs.coeff

Matrix([
[0],
[0],
[1]])

In [82]:
np.asarray(dx1.coeff)

array([[1],
       [0],
       [0]], dtype=object)

In [84]:
np.asarray(hs.coeff)

array([[0],
       [-1],
       [0]], dtype=object)

In [29]:
(dx2.hodge_star()).coeff

Matrix([
[ 0],
[-1],
[ 0]])

In [37]:
x1

x1

In [42]:
hs = dx2.hodge_star()

In [78]:
hs.get_baseform_from_idcs(tuple([1,2]))

(1)dx2^dx3

In [77]:
hs.get_coeff(hs.get_baseform_from_idcs(tuple([1,2])))

0

In [100]:
def hodge_star():
    

SyntaxError: unexpected EOF while parsing (<ipython-input-100-181144691d3a>, line 1)

In [101]:
space = np.asarray([np.sqrt(2)/2, np.sqrt(2)/2])


array([[0.5, 0.5],
       [0.5, 0.5]])

In [109]:
np.linalg.svd(np.identity(2) - np.outer(space, space))

(array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([1.00000000e+00, 3.14018492e-16]),
 array([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]]))