In [10]:
import matplotlib
matplotlib.use('Agg')
import os
import datetime
import numpy as np
import dill as pickle
import random
import sys
np.random.seed(0)
random.seed(0)
now = datetime.datetime.now().strftime("%B_%d_%Y_%H_%M_%S")
workingdirectory = os.popen('git rev-parse --show-toplevel').read()[:-1]
sys.path.append(workingdirectory)
os.chdir(workingdirectory)
#print(os.getcwd())
from codes.experimentclasses.RigidEthanolXYZ import RigidEthanolXYZ
#from codes.otherfunctions.multirun import get_coeffs_reps
#from codes.otherfunctions.multirun import get_grads_reps_pca2
#from codes.otherfunctions.multiplot import plot_betas, plot_betas2reorder
from codes.geometer.RiemannianManifold import RiemannianManifold


In [11]:
n = 10000
natoms = 9
n_components = 3
itermax = 10000
tol = 1e-10
lambdas = np.asarray([0.,0.0001,.001,.01,.1,1,10,100], dtype = np.float16)
nsel = 25
#sample_pts = np.random.choice(list(range(n)),nsel,replace = False)
n_neighbors = 100
#nsample = len(sample_pts)
diffusion_time = .05
dim = 2
#filename = '/Users/samsonkoelle/Desktop/NIPScode2018/ethanolangles.npz'
filename = 'doesntmatter'
cor = 0.
noise = False
var= 0.
cores = 3
atoms4 = np.asarray([[6,1,0,4],[4,0,2,8],[7,6,5,1],[3,0,2,4]],dtype = int)
experiment = RigidEthanolXYZ(dim, cor,var, cores, noise, atoms4)
#experiment = RigidEthanolXYZ(dim, 9,n,0.0,0.0001)
experiment.M = experiment.load_data()
experiment.M.geom = experiment.M.compute_geom_brute(diffusion_time = diffusion_time, n_neighbors = n_neighbors)
#experiment.M.geom = experiment.M.compute_geom(diffusion_time = diffusion_time, n_neighbors = n_neighbors)


[[  0.          0.          0.       ]
 [-10.          0.          0.       ]
 [  0.         10.          0.       ]
 [  0.         -0.5         0.8660254]
 [  0.         -0.5        -0.8660254]
 [-10.          1.          0.       ]
 [-10.         -0.5         0.8660254]
 [-10.         -0.5        -0.8660254]
 [  1.         10.          0.       ]]
[[  0.          0.          0.       ]
 [-10.          0.          0.       ]
 [  0.         10.          0.       ]
 [  0.         -0.5         0.8660254]
 [  0.         -0.5        -0.8660254]
 [-10.          1.          0.       ]
 [-10.         -0.5         0.8660254]
 [-10.         -0.5        -0.8660254]
 [  1.         10.          0.       ]]


/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:133: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  SparseEfficiencyWarning)
/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:202: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  'is in the CSC matrix format', SparseEfficiencyWarning)


In [12]:
experiment.N = experiment.M.get_embedding3(experiment.M.geom, n_components, diffusion_time, 2)


In [13]:
dg_x = experiment.get_dx_g_full(experiment.M.data[np.asarray([0,1])])

/Users/samsonkoelle/manifoldflasso_jmlr/codes/experimentclasses/RigidEthanolXYZ.py:366: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  positions4 = torch.tensor(positions4, requires_grad=True)


TypeError: 'NoneType' object is not subscriptable

In [ ]:
from codes.geometer.ShapeSpace import ShapeSpace
from codes.geometer.TangentBundle import TangentBundle

def get_grads(self, M, N , selected_points):
    dimnoise = 2
    tangent_bases = self.M.get_wlpca_tangent_sel(M, selected_points)
    subM = RiemannianManifold(M.data[selected_points], dim)
    subM.tb = TangentBundle(subM, tangent_bases)
    N.tangent_bundle = TangentBundle(N, N.geom.rmetric.embedding_eigenvectors)
    df_M = self.get_dF_js_idM(M, N, subM.tb, N.tangent_bundle,selected_points,dimnoise)        #experiments[i].df_M = experiments[i].df_M / np.linalg.norm(experiments[i].df_M, axis=1).sum(axis=0)
    df_M2 = df_M / np.linalg.norm(df_M) ** 2
    dg_x = self.get_dx_g_full(M.data[selected_points])
    #W = ShapeSpace(self.positions, M.data)
    #dw = W.get_dw(cores, self.atoms3, self.natoms, selected_points)
    #dg_w = self.project(np.swapaxes(dw, 1, 2),self.project(dw, dg_x))
    dgx_norm = self.normalize(dg_x)
    dg_M = self.project(subM.tb.tangent_bases, dgx_norm)
    return(df_M2, dg_M)



In [8]:
dg_x = experiment.get_dx_g_full(experiment.M.data[np.asarray([0,1])])

/Users/samsonkoelle/manifoldflasso_jmlr/codes/experimentclasses/RigidEthanolXYZ.py:366: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  positions4 = torch.tensor(positions4, requires_grad=True)


TypeError: 'NoneType' object is not subscriptable

In [5]:
dg_x

NameError: name 'dg_x' is not defined

In [9]:
experiment.get_dx_g_full(experiment.M.data)

/Users/samsonkoelle/manifoldflasso_jmlr/codes/experimentclasses/RigidEthanolXYZ.py:366: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  positions4 = torch.tensor(positions4, requires_grad=True)


TypeError: 'NoneType' object is not subscriptable

In [28]:
dg_x = experiment.get_dx_g_full(experiment.M.data[np.asarray([0,1])])

[[2 0 1 5]
 [3 0 1 5]
 [4 0 1 5]
 [2 0 1 6]
 [3 0 1 6]
 [4 0 1 6]
 [2 0 1 7]
 [3 0 1 7]
 [4 0 1 7]
 [1 0 2 8]
 [3 0 2 8]
 [4 0 2 8]]


/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/ipykernel_launcher.py:670: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


TypeError: 'NoneType' object is not subscriptable

In [18]:
experiment.get_dx_g_xyz(experiment.M.data[0])

[[2 0 1 5]
 [3 0 1 5]
 [4 0 1 5]
 [2 0 1 6]
 [3 0 1 6]
 [4 0 1 6]
 [2 0 1 7]
 [3 0 1 7]
 [4 0 1 7]
 [1 0 2 8]
 [3 0 2 8]
 [4 0 2 8]]


/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/ipykernel_launcher.py:670: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


TypeError: 'NoneType' object is not subscriptable

In [27]:
experiment.M.data.shape


(10000, 27)

In [16]:
help(experiment.get_dx_g_xyz)

Help on method get_dx_g_xyz in module __main__:

get_dx_g_xyz(x) method of __main__.RigidEthanolXYZ instance



In [19]:
        #def get_dx_g_xyz(self, x):
        self = experiment
        x = experiment.M.data[0]
        atoms4 = self.atoms4
        print(atoms4)
        # atoms3 = self.atoms3
        # p = len(atoms4)
        p = self.p
        # combos = np.asarray([[0,1,2],[1,2,3],[0,2,3],[0,1,3]])
        # d = atoms3.shape[0] * 3
        d = self.d
        output = np.zeros((d, p))
        # loop over tetrehedra
        for k in range(p):
            atom4 = atoms4[k, :]
            x4 = np.zeros((4, 3))
            for i in range(4):
                x4[i, :] = x[(atom4[i] * 3):(atom4[i] * 3 + 3)]
            x4 = np.asarray(x4)
            fitin = self.g4(x4, True)
            for i in range(4):
                # a = atoms3[actived[i]]
                for j in range(3):
                    # plus the lowest index first
                    output[3 * atom4[i] + j, k] = fitin[1][i, j]
        #return (output)

[[2 0 1 5]
 [3 0 1 5]
 [4 0 1 5]
 [2 0 1 6]
 [3 0 1 6]
 [4 0 1 6]
 [2 0 1 7]
 [3 0 1 7]
 [4 0 1 7]
 [1 0 2 8]
 [3 0 2 8]
 [4 0 2 8]]


/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/ipykernel_launcher.py:670: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


TypeError: 'NoneType' object is not subscriptable

In [26]:
fitin

(tensor(0., dtype=torch.float64, grad_fn=<AcosBackward>), None)

In [23]:
self.g4(x4, True)

/Users/samsonkoelle/anaconda3/envs/manifold_env_april/lib/python3.5/site-packages/ipykernel_launcher.py:670: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


(tensor(0., dtype=torch.float64, grad_fn=<AcosBackward>), None)